language: java
install: true
dist: trusty

jdk: openjdk10

before_script:
  - chmod +x gradlew

script:
  # Install OpenJDK 14
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - chmod +x $TRAVIS_BUILD_DIR/install-jdk.sh
  - export JAVA_HOME=$HOME/openjdk14
  - $TRAVIS_BUILD_DIR/install-jdk.sh -f 14 --target $JAVA_HOME

  - ./gradlew build check jacocoTestReport --stacktrace

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
